image: node:latest

stages:
  - static
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

eslint:
  stage: static
  script:
    - npm install
    - npm run lint

unit tests:
  stage: static
  script:
    - npm run unit

build:
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/kairatjc/proquality:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/kairatjc/proquality:$CI_COMMIT_SHA

e2e tests:
  stage: test
  script:
    - npm run e2e

flaky tests:
  stage: test
  allow_failure: true
  script:
    - npm run flaky

deploy:
  stage: deploy
  services:
    - name: docker:20.10.16-dind
      alias: docker
  image: docker:20.10.16
  script:
    - docker run registry.gitlab.com/kairatjc/proquality:$CI_COMMIT_SHA e2e
