name: Basic workflow

on:
  push:
    branches: [ "master" ]

jobs:
  static:
    name: static tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: install packages
        run: npm install

      - name: linter
        run: npm run lint

      - name: unit tests
        run: npm run unit

  build_and_push:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/kairatjc/proquality-actions:latest
          docker push ghcr.io/kairatjc/proquality-actions:latest

      - name: e2e tests
        run: docker run ghcr.io/kairatjc/proquality-actions:latest e2e
      
      - name: flaky tests
        run: docker run ghcr.io/kairatjc/proquality-actions:latest flaky
